### ISSUE TITLE
Fields without hummus tags can't follow fields with array hummus tags

### ISSUE THREAD

**Issue by rainmaker** [aditya87/hummus#1]
Hi Adi,

Here's the description for our issue so you have it captured here:

Given a struct like:
```
type Config struct {
  OpsmanNetworkName string `json:"ops_manager_subnet" hummus:"networks_configuration.networks[0].name,omitempty"`
  OpsmanSubnetIDList []string `json:"ops_manager_subnet_list"` 
}
```
We receive the error `invalid struct tag json:"ops_manager_subnet_list"`
Looks like hummus assumes that the struct fields following a field with an “array” tag are also in the array. 

It's also not ideal that fields with array tags must be defined in order of desired array index. It looks like this may be addressed along with the above issue, according to your README, so we'd like to +1 that.

Let us know if it would be better for us to fork this, or if you need more context.

Thanks!
Raina and Dave
PCF RelEng

**Comment by aditya87** [comment]
Hi Raina and Dave,

Thanks for pointing this out! This issue has been fixed in v2 of hummus. You can now specify arrays out of order and this bug is gone as a result. Please see the github releases page.

Thanks,
-Adi
